# See https://pre-commit.com for more information

files: .*\.py$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        files: ''
      - id: debug-statements
        files: .*\.py$
  - repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v5.0.4
    hooks:
      - id: pyproject-flake8